### ISSUE TITLE
RuntimeError while executing pipeline = Text2RoomPipeline(args, first_image_pil=first_image_pil)

### ISSUE THREAD

**Issue by raRabit** [lukasHoel/text2room#11]
(text2room) XXX@vrlab166:~/文档/XXX/text2room-main$ python generate_scene.py 
Fetching 13 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 251271.67it/s]
/home/XXX/anaconda3/envs/text2room/lib/python3.9/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Fetching 13 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 8605.74it/s]
Using cache found in /home/XXX/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master
Traceback (most recent call last):
  File "/home/XXX/文档/XXX/text2room-main/generate_scene.py", line 71, in <module>
    main(args)
  File "/home/XXX/anaconda3/envs/text2room/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/XXX/文档/XXX/text2room-main/generate_scene.py", line 31, in main
    pipeline = Text2RoomPipeline(args, first_image_pil=first_image_pil)
  File "/home/XXX/文档/XXX/text2room-main/model/text2room_pipeline.py", line 62, in __init__
    self.setup_models()
  File "/home/XXX/文档/XXX/text2room-main/model/text2room_pipeline.py", line 108, in setup_models
    self.iron_depth_n_net, self.iron_depth_model = load_iron_depth_model(self.args.iron_depth_type, self.args.iron_depth_iters, self.args.models_path, self.args.device)
  File "/home/XXX/文档/XXX/text2room-main/model/iron_depth/predict_depth.py", line 33, in load_iron_depth_model
    n_net = NNET(args).to(device)
  File "/home/XXX/文档/XXX/text2room-main/model/iron_depth/models_normal/NNET.py", line 14, in __init__
    self.n_net = EESNU(BN=True)
  File "/home/XXX/文档/XXX/text2room-main/model/iron_depth/models_normal/submodules.py", line 11, in __init__
    self.encoder = Encoder()
  File "/home/XXX/文档/XXX/text2room-main/model/iron_depth/models_normal/submodules.py", line 132, in __init__
    basemodel = torch.hub.load('rwightman/gen-efficientnet-pytorch', basemodel_name, pretrained=True)
  File "/home/XXX/anaconda3/envs/text2room/lib/python3.9/site-packages/torch/hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/XXX/anaconda3/envs/text2room/lib/python3.9/site-packages/torch/hub.py", line 572, in _load_local
    model = entry(*args, **kwargs)
  File "/home/XXX/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/gen_efficientnet.py", line 1120, in tf_efficientnet_b5_ap
    model = _gen_efficientnet(
  File "/home/XXX/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/gen_efficientnet.py", line 544, in _gen_efficientnet
    model = _create_model(model_kwargs, variant, pretrained)
  File "/home/XXX/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/gen_efficientnet.py", line 290, in _create_model
    load_pretrained(model, model_urls[variant])
  File "/home/XXX/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/helpers.py", line 39, in load_pretrained
    state_dict = load_state_dict_from_url(url, progress=False, map_location='cpu')
  File "/home/XXX/anaconda3/envs/text2room/lib/python3.9/site-packages/torch/hub.py", line 735, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/XXX/anaconda3/envs/text2room/lib/python3.9/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/XXX/anaconda3/envs/text2room/lib/python3.9/site-packages/torch/serialization.py", line 1020, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 14950 more bytes. The file might be corrupted.

**Comment by raRabit** [comment]
I encountered this problem when configuring the environment. Please tell me how to solve it if you have encountered this problem, thank you!

**Comment by lukasHoel** [comment]
Which pytorch version are you using? Can you try to re-install it. It seems this is an error while loading a pretrained model from torch hub.

**Comment by raRabit** [comment]
I am using pytorch=1.13.1,CUDA 11.7, pytorch3D 0.7.3 because the stablev version of pytorch3D is 0.7.3 . I 'll try to re-install 0.7.2

**Comment by raRabit** [comment]
Sorry to bother you. I reinstalled the pytorch, but the error message above still occurs.

**Comment by lukasHoel** [comment]
I just re-downloaded the pretrained model ```rwightman/gen-efficientnet-pytorch``` without issues.
So the problem has to be in your local cache.
I suggest you delete your ```/home/XXX/.cache/torch/hub/rwightman_*``` and let the model be pulled again on the next run.

**Comment by raRabit** [comment]
I eventually found out that all problems were caused by the unstable network. Finally, I successfully ran this project by loading the model locally.
