### ISSUE TITLE
ImportError: DLL load failed while importing _C: Not found procedure

### ISSUE THREAD

**Issue by ProximaCA** [lukasHoel/text2room#26]
C:\Users\anon\Desktop\text2room-main>python generate_scene.py
Traceback (most recent call last):
  File "C:\Users\anon\Desktop\text2room-main\generate_scene.py", line 5, in <module>
    from model.text2room_pipeline import Text2RoomPipeline
  File "C:\Users\anon\Desktop\text2room-main\model\text2room_pipeline.py", line 12, in <module>
    from model.mesh_fusion.util import (
  File "C:\Users\anon\Desktop\text2room-main\model\mesh_fusion\util.py", line 6, in <module>
    from pytorch3d.renderer import FoVPerspectiveCameras, PerspectiveCameras
  File "C:\Users\anon\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch3d-0.7.3-py3.9-win-amd64.egg\pytorch3d\renderer\__init__.py", line 7, in <module>
    from .blending import (
  File "C:\Users\anon\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch3d-0.7.3-py3.9-win-amd64.egg\pytorch3d\renderer\blending.py", line 10, in <module>
    from pytorch3d import _C
    
ImportError: DLL load failed while importing _C: Not found procedure

**Comment by lukasHoel** [comment]
I never tested pytorch3D  on windows. This error indicates that the cuda extensions of pytorch3D were not compiled.
